"""Added email to User and created_at to Board.

Revision ID: 48d2eebce5d6
Revises: 
Create Date: 2025-04-22 14:37:14.729495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '48d2eebce5d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.String(length=300), nullable=True))
        batch_op.drop_column('eontent')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('address')

    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eontent', mysql.VARCHAR(length=300), nullable=True))
        batch_op.drop_column('content')

    # ### end Alembic commands ###
